### ISSUE TITLE
Improve Printer Analysis

### ISSUE THREAD

**Issue by strawgate** [strawgate/C3-Inventory#1]
Add support for Mac OS printers

**Comment by jgstew** [comment]
I just added a bunch of Mac printer relevance to BigFixMe a bit ago.

**Comment by strawgate** [comment]
I'm going to change this to a Mac Printer Analysis issue and create a new one for the Windows one. The Windows one is now #11

**Comment by strawgate** [comment]
Fixed by a62d93a6ce09c87301179e4fff7b5b85f201f24c
