### ISSUE TITLE
Dell Warranty Content is not working

### ISSUE THREAD

**Issue by strawgate** [strawgate/C3-Inventory#22]
API Key required

**Comment by strawgate** [comment]
Maybe I can include a fixlet to distribute the API key to the endpoints and then store it in a client setting or registry key?

**Comment by strawgate** [comment]
Could also just get an API key, encode it, and hope Dell doesn't notice

**Comment by jgstew** [comment]
This issue refers to this content: https://bigfix.me/fixlet/details/20528

Related: 
- https://bigfix.me/fixlet/details/6048
- https://bigfix.me/analysis/details/2994797

I think the fixlet needs relevance added to it to cause it to distribute over time so it doesn't overrun dell's api limits.

I'm using the API key found within Dell's own software. Not sure if it still works, but if they have invalidated it, then it will stop their own software from working. It should be possible to pull their API key all over again, though I don't know that I documented how I did it last time.

**Comment by strawgate** [comment]
This has been fixed by bfa6f54397010165eaa9ae1f67b012127d08fd2d -- new gather fixlet and analysis.

The old analysis was renamed instead of replaced in order to preserve any values that were already collected.

My general philosophy is to keep targeting relevance out of fixlet/task relevance for the most part. For probes especially I think I probably need to do a better job of removing the default action, including information about how to properly target it in the fixlet description, and providing documentation in the C3 Inventory site.

Obviously this has a higher chance of being misused but I think with the right language and documentation in place we can prevent it from being a surprise.
