### ISSUE TITLE
Hardware - Network Adapters - Universal 

### ISSUE THREAD

**Issue by mbrownr** [strawgate/C3-Inventory#32]
The operator "descriptions" is not defined on Mac

**Comment by jgstew** [comment]
So the `Hardware - Network Adapters - Universal` property in the `Hardware - Universal` [analysis](https://github.com/strawgate/C3-Inventory/blob/master/Analyses/Hardware%20-%20Universal.bes) reports an error on Mac?

Seems like these might be the next best options for Mac: 
- https://developer.bigfix.com/relevance/reference/network-adapter.html#friendly-name-of-network-adapter-string
- https://developer.bigfix.com/relevance/reference/network-adapter.html#name-of-network-adapter-string

It seems like the [description](https://developer.bigfix.com/relevance/reference/network-adapter.html#description-of-network-adapter-string) option is windows only :(

**Comment by strawgate** [comment]
I agree -- we'll just do a check and pick which descriptor to use
