### ISSUE TITLE
OS - License Status - Windows

### ISSUE THREAD

**Issue by tbriggs275336** [strawgate/C3-Inventory#33]
Reports <error> on Windows 2008r2 and Windows 2008

**Comment by jgstew** [comment]
So the `OS - License Status - Windows` property in the `Operating System - Windows` [analysis](https://github.com/strawgate/C3-Inventory/blob/master/Analyses/Operating%20System%20-%20Windows.bes) doesn't work correctly on Win2008 & r2?

Does it report anything? Nothing?

**Comment by strawgate** [comment]
I was there when he made this comment -- I think it may report an error on 2008r2 and 2008 @jgstew

**Comment by jgstew** [comment]
I think I came across something related: https://bigfix.me/relevance/details/3019080

`(Name LIKE 'Windows(R)%25' or Name LIKE 'Windows Server(R)%25')`

And by me, I mean you.
